apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-inc
spec:
  schedule: "* * * * *" # every minute
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: auto-inc
              image: curlimages/curl:8.17.0
              command: ["sh", "-c"]
              args: ["curl -X POST http://counter-app-service/inc"]
          restartPolicy: OnFailure